apiVersion: apps/v1
kind: Deployment
metadata:
  name: rob-app
spec:
  selector:
    matchLabels:
      run: rob-app
  replicas: 2
  template:
    metadata:
      labels:
        run: rob-app
    spec:
      containers:
        - name: rob-app
          image: kicbase/echo-server:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rob-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: rob-app
  type: LoadBalancer
